# Generated by Django 5.1.2 on 2024-10-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=80)),
                ('CompanyNIT', models.CharField(max_length=12)),
                ('ContactPerson', models.CharField(blank=True, max_length=80)),
                ('Tel1', models.CharField(blank=True, max_length=15)),
                ('Tel2', models.CharField(blank=True, max_length=15)),
                ('Email', models.CharField(blank=True, max_length=80)),
                ('Ciudad', models.CharField(blank=True, max_length=25)),
                ('Addrs', models.CharField(blank=True, max_length=80)),
                ('Comment', models.TextField(blank=True)),
            ],
        ),
    ]
