# Generated by Django 5.1.2 on 2024-10-29 00:59

import django.db.models.deletion
import suppliers_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('file', models.FileField(upload_to=suppliers_app.models.upload_invoice)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='suppliers_app.supplier')),
            ],
        ),
    ]
