# Generated by Django 5.1.2 on 2024-10-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0002_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.IntegerField(blank=True),
        ),
    ]
