# Generated by Django 5.1.2 on 2024-11-14 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0004_invoice_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='value',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paidValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totalValue',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers_app.invoice')),
            ],
        ),
    ]
