# Generated by Django 5.1.2 on 2024-11-14 00:53

import suppliers_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0005_remove_invoice_value_invoice_paidvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='payment',
            name='file',
            field=models.FileField(blank=True, upload_to=suppliers_app.models.upload_payment),
        ),
        migrations.AddField(
            model_name='payment',
            name='paidValue',
            field=models.IntegerField(default=0),
        ),
    ]
