# Generated by Django 5.1.2 on 2024-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0007_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
