# Generated by Django 5.1.2 on 2024-11-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0008_alter_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='supplier',
            new_name='invoice',
        ),
    ]
