# Generated by Django 5.1.3 on 2024-11-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_app', '0009_rename_supplier_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Factura', max_length=80),
        ),
    ]
